### PR TITLE
Cache the servers on Minehut

### PR DESCRIPTION
**Pull request by DebitCardz**
Increases display speed of options when using `/server`.
Depends on #4

### CODE REVIEW

**Comment by DebitCardz** [comment]
I personally think for the use case we have here where we need semi-accurate data just polling every 30 seconds would be better so if nobody has recently done the command the data wont be weird.
I don't think it matters too much which approach is taken here but the suggestions will definitely be more inaccurate for users who use the command after periods of inactivity.

**Comment by SantioMC** [comment]
How so? It would be something like this flow:
Person runs /server:
 -> if cache is over 30s or not set yet:
    -> cache current servers online
 -> use the cache for the autocomplete

**Comment by DebitCardz** [comment]
Yeah, that's why I think it's ok whichever approach is taken, just having the most up to date data every 30 seconds without user input seems a tad bit nicer but it's honestly probably fine.

LGTM.

**Comment by SantioMC** [comment]
Sorry for the delay, thought I've already merged this; lgtm 👌🏻

**Pull request merged**
