### PR TITLE
Silent Tags

### PR DESCRIPTION
**Pull request by tarna**
This PR adds a feature where if you send a tag as a silent message, it will delete your original message. 

For example "@ silent !test". (without the space between the @ and silent)

This is useful because users sometimes send a tag and manually delete it themselves so the user it's for doesn't try to run it again. And sending the tag like this will automatically do it for you.

### CODE REVIEW

**Comment by SantioMC** [comment]
I like the idea of having silent tags, however I don't think having this as a way to trigger them would be a good way of doing it, I can see cases where you may want to do this but accidentally have the message deleted

**Comment by tarna** [comment]
> I like the idea of having silent tags, however I don't think having this as a way to trigger them would be a good way of doing it, I can see cases where you may want to do this but accidentally have the message deleted

What other way could we do it? Also, what do you mean by the last part?

**Comment by SantioMC** [comment]
Another way we could possible implement auto deleting tags is by forcing the message to end with like `-delete` or something similar where it's very clear that the message is intended to be deleted by the bot, the issue with what's currently implemented is you could do `@Santio contact !support` and that would delete your message

**Comment by tarna** [comment]
Nope, it should not trigger for that. It uses Discord's silent message feature. Whenever you start a message with `@silent`, Discord will not send a notification for that. This utilizes that where if a message has the notifications suppressed tag, it will delete the original message. The `@silent` part isn't an actual user tag.

**Comment by flowergardn** [comment]
i believe @ silent is pretty standard and would work excellent for this use case

**Comment by SantioMC** [comment]
> Nope, it should not trigger for that. It uses Discord's silent message feature. Whenever you start a message with `@silent`, Discord will not send a notification for that. This utilizes that where if a message has the notifications suppressed tag, it will delete the original message. The `@silent` part isn't an actual user tag.

Ah gotcha, wasn't aware that was a feature, I'm down to implement this then

**Pull request merged**
